version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8880:80"
        depends_on:
            - app
        container_name: my_project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        depends_on:
            - db
        container_name: my_project_app

    db:
        image: postgres:18
        restart: always
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: my_project
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "8110:3306"
        container_name: my_project_db
